version: 2
updates:
  # Mantener actualizadas las dependencias de npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "your-username" # Reemplaza con tu username de GitHub
    assignees:
      - "your-username"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    ignore:
      # Ignorar dependencias que requieren actualización manual
      - dependency-name: "@vonsim/*"
        update-types: ["version-update:semver-major"]

  # Mantener actualizadas las dependencias de npm en la app
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "app"
    ignore:
      - dependency-name: "@vonsim/*"
        update-types: ["version-update:semver-major"]

  # Mantener actualizadas las dependencias de npm en packages
  - package-ecosystem: "npm"
    directory: "/packages/assembler"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "assembler"

  - package-ecosystem: "npm"
    directory: "/packages/simulator"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "simulator"

  - package-ecosystem: "npm"
    directory: "/packages/common"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "common"

  # Mantener actualizadas las GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "github-actions"
