version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ruiz-jose"
    assignees:
      - "ruiz-jose"
    labels:
      - "dependencies"
      - "automated"
      - "security"
    ignore:
      - dependency-name: "@vonsim/*"
        update-types: ["version-update:semver-major"]
    versioning-strategy: "increase"

  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:30"
    open-pull-requests-limit: 10
    reviewers:
      - "ruiz-jose"
    assignees:
      - "ruiz-jose"
    labels:
      - "dependencies"
      - "automated"
      - "app-dependencies"
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "@vonsim/*"
        update-types: ["version-update:semver-major"]

  # Mantener actualizadas las dependencias de npm en packages
  - package-ecosystem: "npm"
    directory: "/packages/assembler"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "assembler"

  - package-ecosystem: "npm"
    directory: "/packages/simulator"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "simulator"

  - package-ecosystem: "npm"
    directory: "/packages/common"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "common"

  # Mantener actualizadas las GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "github-actions"
