version: 2
updates:
  # Actualización de dependencias npm en raíz
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00" # Ajustado al horario local (-03:00)
    open-pull-requests-limit: 10
    reviewers:
      - "ruiz-jose" # Usuario real
    assignees:
      - "ruiz-jose"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "security"
    ignore:
      - dependency-name: "@vonsim/*"
        update-types: ["version-update:semver-major"]
    versioning-strategy: "increase"

  # Actualización de dependencias npm en /app
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:30" # 30 minutos después de la actualización raíz
    open-pull-requests-limit: 10
    reviewers:
      - "ruiz-jose"
    assignees:
      - "ruiz-jose"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "app-dependencies"
    versioning-strategy: "increase"
    security-advisories: true
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "app"
    ignore:
      - dependency-name: "@vonsim/*"
        update-types: ["version-update:semver-major"]

  # Mantener actualizadas las dependencias de npm en packages
  - package-ecosystem: "npm"
    directory: "/packages/assembler"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "assembler"

  - package-ecosystem: "npm"
    directory: "/packages/simulator"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "simulator"

  - package-ecosystem: "npm"
    directory: "/packages/common"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "common"

  # Mantener actualizadas las GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "your-username"
    assignees:
      - "your-username"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "github-actions"
